package ca.mcmaster.se2aa4.island.team012.States;

public enum Status {
    FIND_LENGTH_STATE, FIND_WIDTH_STATE, APPROACH_ISLAND_STATE, CREEK_FINDING_STATE, SPIRAL_SEARCH_STATE, LOCATING_ISLAND_STATE,END_SEARCH_STATE
}
