package ca.mcmaster.se2aa4.island.team012.States;

public enum Status {
    WIDTH_ALIGN_STATE,LENGTH_ALIGN_STATE, FIND_LENGTH_STATE, FIND_WIDTH_STATE, APPROACH_ISLAND_STATE, END_SEARCH_STATE, SPIRAL_FROM_MIDDLE_STATE, SPIRAL_FROM_SITE_STATE, LEFT_TURN_STATE
}
